[package]
name = "helloworld"
description = "Evolving Hello World."
version = "1.0.0"
authors = ["pkalivas <peterkalivas@gmail.com>"]

[dependencies]
radiate_legacy={path= "../../radiate_legacy" }
rand="*"