[package]
name = "xor-evtree"
description = "XOR for redox using evtree."
version = "1.0.0"
authors = ["pkalivas <peterkalivas@gmail.com>"]

[dependencies]
simple-matrix="*"
radiate_legacy={path= "../../radiate_legacy" }
radiate_legacy_matrix_tree={path= "../../radiate_legacy_matrix_tree" }
