[package]
name = "lstm-neat"
description = "XOR for the neat algorithm."
version = "1.0.0"
authors = ["pkalivas <peterkalivas@gmail.com>"]

[dependencies]
radiate_legacy={path= "../../radiate_legacy" }
serde = "*"
serde_json="*"
uuid = { version = "0.8", features = ["serde", "v4"] }
